---
patients: data/patients.tsv
samples: data/samples.tsv


ref:
  genome: "/data/Robinson-SB/PathSeq-data/pathseq_host.fa"


params:
  PathSeq: ""
trimming:
  skip: True

Kraken:
  db_path: "/data/Robinson-SB/Kraken-data"
  dbname: "pathseqDB"
  taxonomic_rank: "genus"
  microbe_fasta: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa"

PathSeq:
  bam_file: "output/BAM/{patient}-{sample}-unaligned.bam"
  microbe_fasta: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa"
  microbe_bwa_image: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa.img"
  taxonomy_db: "/data/Robinson-SB/PathSeq-data/pathseq_taxonomy.db"
  host_img: "/data/Robinson-SB/PathSeq-data/pathseq_host.fa.img"
  host_bfi: "/data/Robinson-SB/PathSeq-data/pathseq_host.bfi"
