---
patients: data/patients.tsv
samples: data/samples.tsv


ref:
  genome: "/data/Robinson-SB/PathSeq-data/pathseq_host.fa"


params:
  PathSeq:
    filter: '--java-options "-Xmx48g -Xms48G -Djava.io.tmpdir=/lscratch/$SLURM_JOBID/tmp -XX:+UseG1GC -XX:ParallelGCThreads=8 -XX:ConcGCThreads=2" --spark-master local[4]'
    BWA: '--java-options "-Xmx48g -Xms48G -Djava.io.tmpdir=/lscratch/$SLURM_JOBID/tmp -XX:+UseG1GC -XX:ParallelGCThreads=8 -XX:ConcGCThreads=2" --spark-master local[4]'
    pipeline: '--java-options "-Xmx48g -Xms48G -Djava.io.tmpdir=/lscratch/$SLURM_JOBID/tmp -XX:+UseG1GC -XX:ParallelGCThreads=8 -XX:ConcGCThreads=2" --spark-master local[4]'
  Kraken: '--threads 16 '
trimming:
  skip: True

Kraken:
  db_path: "/data/Robinson-SB/Kraken-data"
  dbname: "pathseqDB"
  taxonomic_rank: "genus"
  microbe_fasta: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa"

PathSeq:
  bam_file: "output/BAM/{patient}-{sample}-unaligned.bam"
  microbe_fasta: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa"
  microbe_bwa_image: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa.img"
  taxonomy_db: "/data/Robinson-SB/PathSeq-data/pathseq_taxonomy.db"
  host_img: "/data/Robinson-SB/PathSeq-data/pathseq_host.fa.img"
  host_bfi: "/data/Robinson-SB/PathSeq-data/pathseq_host.bfi"
