---
patients: data/patients.tsv
samples: data/samples.tsv


params:
  PathSeq: "--min-score-identity .7 --is-host-aligned false --filter-duplicates false --skip-quality-filters true "
  STAR: ""

PathSeq:
  bam_file: "BAM/trimmed/{patient}-{sample}_merged.bam"
  microbe_fasta: "../Aulicino2018/data/microbev1.fa"
  microbe_fai: "../Aulicino2018/data/microbev1.fa.fai"
  microbe_dict: "../Aulicino2018/data/microbev1.dict"
  microbe_bwa_image: "../Aulicino2018/data/microbev1.fa.img"
  taxonomy_db: "../Aulicino2018/data/microbev1_release201_taxonomy.db"
  host_img: "/data/Robinson-SB/PathSeq-data/pathseq_host.fa.img"
  host_bfi: "/data/Robinson-SB/PathSeq-data/pathseq_host.bfi"
