---
patients: data/patients.tsv
samples: data/samples.tsv

ref:
  annotation: "raw/genome/gencodev34_ERCC92.gtf"
  genome: "raw/genome/Hg38_ERCC92.fasta"

human_ref:
  genome: "raw/genome/GRCh38.primary_assembly.genome.fa"
  annotation: "raw/genome/gencode.v34.annotation.gtf"

params:
  PathSeq: "--min-score-identity .7 --is-host-aligned true --filter-duplicates true "
trimming:
  skip: True


PathSeq:
  bam_file: "output/star/{patient}-{sample}/_STARpass2/Aligned.out.bam"
  microbe_fasta: "/data/Robinson-SB/PathSeq-data/subspecies_genome.fa"
  microbe_fai: "/data/Robinson-SB/PathSeq-data/subspecies_genome.fa.fai"
  microbe_dict: "/data/Robinson-SB/PathSeq-data/subspecies_genome.fa.dict"
  microbe_bwa_image: "/data/Robinson-SB/PathSeq-data/subspecies_genome.fa.img"
  taxonomy_db: "/data/Robinson-SB/PathSeq-data/select-complete-genomes.db"
  host_img: "/data/Robinson-SB/PathSeq-data/pathseq_host.fa.img"
  host_bfi: "/data/Robinson-SB/PathSeq-data/pathseq_host.bfi"
