---
patients: data/patients.tsv
samples: data/samples.tsv

ref:
  annotation: "raw/genome/gencode.v34.chr_patch_hapl_scaff_ERCC92.annotation.gtf"
  genome: "raw/genome/GRCh38.p13.genome_ERCC92.fasta"

human_ref:
  genome: "raw/genome/GRCh38.p13.genome.fa"
  annotation: "raw/genome/gencode.v34.chr_patch_hapl_scaff.annotation.gtf"

params:
  PathSeq: "--min-score-identity .7 --is-host-aligned false --filter-duplicates true "
  STAR: ""
trimming:
  skip: True


PathSeq:
  bam_file: "output/star/{patient}-{sample}/_STARpass2/host.reads.filtered.bam"
  microbe_fasta: "data/subspecies_genome.fa"
  microbe_fai: "data/subspecies_genome.fa.fai"
  microbe_dict: "data/subspecies_genome.dict"
  microbe_bwa_image: "data/subspecies_genome.fa.img"
  taxonomy_db: "data/subspecies_genome.db"
  host_img: "data/GRCh38.p13_ERCC92.img"
  host_bfi: "data/GRCh38.p13_ERCC92.hss"
