---
patients: data/patients.tsv
samples: data/samples.tsv
units: data/units.tsv

ref:
  annotation: "raw/genome/gencode.v34.primary_assembly.ERCC92.annotation.gtf"
  genome: "raw/genome/GRCh38.primary_assembly.ERCC92.genome.fasta"

human_ref:
  genome: "raw/genome/GRCh38.primary_assembly.genome.fa"
  annotation: "raw/genome/gencode.v34.primary_assembly.annotation.gtf"

PathSeq:
  bam_file: "output/star/{patient}-{sample}-{plate}/unaligned.bam"
  microbe_fasta: "/data/Robinson-SB/CSI-Microbes-identification/Aulicino2018/data/microbev1.fa"
  microbe_fai: "/data/Robinson-SB/CSI-Microbes-identification/Aulicino2018/data/microbev1.fa.fai"
  microbe_dict: "/data/Robinson-SB/CSI-Microbes-identification/Aulicino2018/data/microbev1.dict"
  microbe_bwa_image: "/data/Robinson-SB/CSI-Microbes-identification/Aulicino2018/data/microbev1.fa.img"
  taxonomy_db: "/data/Robinson-SB/CSI-Microbes-identification/Aulicino2018/data/microbev1_release201_taxonomy.db"
  host_img: "/data/Robinson-SB/PathSeq-data/pathseq_host.fa.img"
  host_bfi: "/data/Robinson-SB/PathSeq-data/pathseq_host.bfi"

VecScreen:
  contaminant_hits: "/data/Robinson-SB/run-VecScreen/output/microbev1-vecscreen-combined-matches.bed"

STAR:
  FASTQ_dir: "FASTQ/trimmed"

params:
  PathSeq: "--min-clipped-read-length 50 --min-base-quality 1 --max-masked-bases 10 --dust-t 24"
  STAR: ""
  PathSeqScore: ""
  fastp: ""
