---
patients: data/patients.tsv
samples: data/samples.tsv

ref:
  annotation: "raw/genome/gencode.v34.chr_patch_hapl_scaff_ERCC92.annotation.gtf"
  genome: "raw/genome/GRCh38.p13.genome_ERCC92.fasta"

human_ref:
  genome: "raw/genome/GRCh38.p13.genome.fa"
  annotation: "raw/genome/gencode.v34.chr_patch_hapl_scaff.annotation.gtf"

PathSeq:
  bam_file: "output/star/{patient}-{sample}/host.reads.filtered.bam"
  microbe_fasta: "data/microbev1.fa"
  microbe_fai: "data/microbev1.fa.fai"
  microbe_dict: "data/microbev1.dict"
  microbe_bwa_image: "data/microbev1.fa.img"
  taxonomy_db: "data/microbev1_release201_taxonomy.db"
  host_img: "/data/Robinson-SB/PathSeq-data/pathseq_host.fa.img"
  host_bfi: "/data/Robinson-SB/PathSeq-data/pathseq_host.bfi"

STAR:
  FASTQ_dir: "FASTQ/trimmed"

params:
  PathSeq: ""
  STAR: ""
