---
patients: data/patients.tsv
samples: data/samples.tsv

ref:
  annotation: "raw/genome/gencode.v34.chr_patch_hapl_scaff_ERCC92.annotation.gtf"
  genome: "raw/genome/GRCh38.p13.genome_ERCC92.fasta"

human_ref:
  genome: "raw/genome/GRCh38.p13.genome.fa"
  annotation: "raw/genome/gencode.v34.chr_patch_hapl_scaff.annotation.gtf"

PathSeq:
  bam_file: "output/star/{patient}-{sample}/Aligned.combined.bam"
  microbe_fasta: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa"
  microbe_fai: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa.fai"
  microbe_dict: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.dict"
  microbe_bwa_image: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa.img"
  taxonomy_db: "/data/Robinson-SB/PathSeq-data/pathseq_taxonomy.db"
  host_img: "/data/Robinson-SB/PathSeq-data/pathseq_host.fa.img"
  host_bfi: "/data/Robinson-SB/PathSeq-data/pathseq_host.bfi"

STAR:
  FASTQ_dir: "FASTQ/trimmed"

params:
  PathSeq: "--min-score-identity .7 --is-host-aligned true --filter-duplicates false --skip-quality-filters true "
  STAR: ""
