---
patients: data/patients.tsv
samples: data/samples.tsv


ref:
  annotation: "raw/genome/Hg38_v22_RNA_SPIKE.gtf"
  genome: "raw/genome/Hg38_RNA_SPIKE.fasta"

human_ref:
  genome: "/fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta"
  annotation: "raw/genome/gencode.v22.annotation.gtf"

params:
  PathSeq: "--min-score-identity .7 --is-host-aligned true --filter-duplicates true --skip-quality-filters false "
  STAR: " --outFilterScoreMinOverLread 0.33 --outFilterMatchNminOverLread 0.33"

trimming:
  skip: True


PathSeq:
  bam_file: "output/star/{patient}-{sample}/_STARpass2/Aligned.out.bam"
  microbe_dict: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.dict"
  microbe_bwa_image: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa.img"
  taxonomy_db: "/data/Robinson-SB/PathSeq-data/pathseq_taxonomy.db"
  host_img: "output/PathSeq/host.fasta.img"
  host_bfi: "output/PathSeq/host.hss"
