---
patients: data/patients.tsv
samples: data/samples.tsv


ref:
  annotation: "raw/genome/gencode.v34.chr_patch_hapl_scaff_RNAspike.gtf"
  genome: "raw/genome/GRCh38.p13_RNAspike.fasta"

human_ref:
  genome: "raw/genome/GRCh38.p13.genome.fa"
  annotation: "raw/genome/gencode.v34.chr_patch_hapl_scaff.annotation.gtf"

params:
  PathSeq: "--min-score-identity .7 --is-host-aligned false --filter-duplicates false --skip-quality-filters true "
  STAR: "--outFilterMatchNmin .33 --outFilterScoreMinOverLread .33 "

trimming:
  skip: False

STAR:
  FASTQ_dir: "FASTQ/trimmed"

PathSeq:
  bam_file: "output/star/{patient}-{sample}/host.reads.filtered.bam"
  microbe_dict: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.dict"
  microbe_bwa_image: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa.img"
  taxonomy_db: "/data/Robinson-SB/PathSeq-data/pathseq_taxonomy.db"
