---
patients: data/patients.tsv
samples: data/samples.tsv
units: data/units.tsv


ref:
  annotation: "raw/genome/gencode.v34.chr_patch_hapl_scaff_RNAspike.gtf"
  genome: "raw/genome/GRCh38.p13_RNAspike.fasta"

human_ref:
  genome: "raw/genome/GRCh38.p13.genome.fa"
  annotation: "raw/genome/gencode.v34.chr_patch_hapl_scaff.annotation.gtf"

params:
  PathSeq: ""
  STAR: ""

trimming:
  skip: False

STAR:
  FASTQ_dir: "FASTQ/trimmed"

PathSeq:
  bam_file: "output/star/{patient}-{sample}-{plate}/unaligned.bam"
  microbe_fasta: "../Aulicino2018/data/microbev1.fa"
  microbe_fai: "../Aulicino2018/data/microbev1.fa.fai"
  microbe_dict: "../Aulicino2018/data/microbev1.dict"
  microbe_bwa_image: "../Aulicino2018/data/microbev1.fa.img"
  taxonomy_db: "../Aulicino2018/data/microbev1_release201_taxonomy.db"
  host_img: "/data/Robinson-SB/PathSeq-data/pathseq_host.fa.img"
  host_bfi: "/data/Robinson-SB/PathSeq-data/pathseq_host.bfi"
