---
patients: data/patients.tsv
samples: data/samples.tsv

ref:
  annotation: "raw/genome/mouse/gencode.vM24.annotation.gtf"
  genome: "raw/genome/mouse/GRCm38.p6.genome.fa"

params:
  PathSeq: "--filter-duplicates false --min-clipped-read-length 31"
trimming:
  skip: True

PathSeq:
  bam_file: "output/star/{patient}-{sample}/_STARpass2/Aligned.out.bam"
  microbe_fasta: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa"
  microbe_bwa_image: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa.img"
  taxonomy_db: "/data/Robinson-SB/PathSeq-data/pathseq_taxonomy.db"
