---
patients: data/patients.tsv
samples: data/samples.tsv
units: data/units.tsv

trimming:
  skip: True

PathSeq:
  bam_file: "{patient}-{sample}/outs/possorted_genome_bam.bam"
  microbe_fasta: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa"
  microbe_fai: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa.fai"
  microbe_dict: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.dict"
  microbe_bwa_image: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa.img"
  taxonomy_db: "/data/Robinson-SB/PathSeq-data/pathseq_taxonomy.db"

params:
  PathSeq: "--min-score-identity .7 --is-host-aligned true --filter-duplicates false --skip-quality-filters true "
  PathSeqScore: "--min-score-identity .7"

CellRanger:
  genome_dir: "$CELLRANGER_REF300/GRCh38"
  chemistry: "SC3Pv2"
