---
patients: data/patients.tsv
samples: data/samples.tsv

ref:
  annotation: "raw/genome/gencode.v22.annotation.gtf"
  genome: "/fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta"

params:
  PathSeq: "--filter-duplicates true --min-clipped-read-length 31"
trimming:
  skip: True

PathSeq:
  bam_file: "output/star/{patient}-{sample}/_STARpass2/Aligned.out.bam"
  microbe_fasta: "data/D23580+PathSeq.fa"
  microbe_bwa_image: "data/D23580+PathSeq.fa.img"
  taxonomy_db: "data/D23580+PathSeq_taxonomy.db"
