---
patients: data/patients.tsv
samples: data/samples.tsv

ref:
  annotation: "raw/genome/gencode.v22.annotation.gtf"
  genome: "/fdb/GATK_resource_bundle/hg38bundle/Homo_sapiens_assembly38.fasta"

params:
  PathSeq: "--filter-duplicates false --min-clipped-read-length 31"
trimming:
  skip: True

PathSeq:
  bam_file: "output/star/{patient}-{sample}/_STARpass2/Aligned.out.bam"
  microbe_prefix: "salmonella-Aulicino2018"
  microbe_fasta: "data/salmonella-Aulicino2018.fa"
  microbe_bwa_image: "data/salmonella-Aulicino2018.fa.img"
  taxonomy_db: "data/salmonella-Aulicino2018_taxonomy.db"
  microbes_of_interest:
    - "Salmonella enterica subsp. enterica serovar Typhimurium str. SL1344"
    - "Salmonella enterica subsp. enterica serovar Typhimurium str. LT2"
