---
patients: data/patients.tsv
samples: data/samples.tsv
units: data/units.tsv

params:
  PathSeq: ""
  PathSeqScore: ""

PathSeq:
  bam_file: "output/BAM/{patient}-{sample}-unaligned.bam"
  microbe_fasta: "../Aulicino2018/data/microbev1.fa"
  microbe_fai: "../Aulicino2018/data/microbev1.fa.fai"
  microbe_dict: "../Aulicino2018/data/microbev1.dict"
  microbe_bwa_image: "../Aulicino2018/data/microbev1.fa.img"
  taxonomy_db: "../Aulicino2018/data/microbev1_release201_taxonomy.db"
  host_img: "/data/Robinson-SB/PathSeq-data/pathseq_host.fa.img"
  host_bfi: "/data/Robinson-SB/PathSeq-data/pathseq_host.bfi"

CellRanger:
  genome_dir: "$CELLRANGER_REF300/GRCh38"
  chemistry: "auto"
