---

ref:
  genome: "raw/genome/GRCh38.p13.genome.fa"
  annotation: "raw/genome/gencode.v34.chr_patch_hapl_scaff.annotation.gtf"

trimming:
  skip: True

PathSeq:
  bam_file: "output/star/{patient}-{sample}/_STARpass2/Aligned.out.bam"
  microbe_fasta: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa"
  microbe_fai: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa.fai"
  microbe_dict: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.dict"
  microbe_bwa_image: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa.img"
  taxonomy_db: "/data/Robinson-SB/PathSeq-data/pathseq_taxonomy.db"
  host_img: "/data/Robinson-SB/PathSeq-data/pathseq_host.fa.img"
  host_bfi: "/data/Robinson-SB/PathSeq-data/pathseq_host.bfi"

params:
  PathSeq: "--min-score-identity .7 --is-host-aligned true --filter-duplicates false --min-base-quality 1 --max-masked-bases 10 --dust-t 24"
  STAR: " --outFilterScoreMinOverLread 0.66 --outFilterMatchNminOverLread 0.66"
