---
PathSeq:
  bam_file: "output/Puram2017/{patient}-{sample}/unaligned_simulated_bam.bam"
  microbe_fasta: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa"
  microbe_fai: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa.fai"
  microbe_dict: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.dict"
  microbe_bwa_image: "/data/Robinson-SB/PathSeq-data/pathseq_microbe.fa.img"
  taxonomy_db: "/data/Robinson-SB/PathSeq-data/pathseq_taxonomy.db"
  host_img: "/data/Robinson-SB/PathSeq-data/pathseq_host.fa.img"
  host_bfi: "/data/Robinson-SB/PathSeq-data/pathseq_host.bfi"

params:
  PathSeq: "--min-score-identity .7 --is-host-aligned false --filter-duplicates true "
